version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@db:5432/logic101
    depends_on:
      - db
    volumes:
      - ./audio:/app/audio
      - ./.env:/app/.env

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: logic101
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: